services:
  back:
    build: ./back
    ports:
      - "4000:4000"
    volumes:
      - ./back/src:/app/src
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
